language: perl
cache:
  directories:
    # local::lib caching
    - $HOME/perl5
    - maint/cpanfile-git-log
addons:
  apt:
    packages:
      - libjpeg-dev
      - libtiff4-dev
      - libpng12-dev
      - libfreetype6-dev
      - libgif-dev
      - libx11-dev
      - libxml2-dev
      - libpango1.0-dev
      - libcairo2-dev
      - aspell     # for dzil Test::PodSpelling
      - aspell-en  # for dzil Test::PodSpelling
matrix:
  include:
    - perl: "5.16"
      os: linux
      dist: trusty
      sudo: false
    - perl: "5.18"
      env: COVERAGE=1   # enables coverage+coveralls reporting
      os: linux
      dist: trusty
      sudo: false
    - perl: "5.20"
      os: linux
      dist: trusty
      sudo: false
    - perl: "blead"
      os: linux
      dist: trusty
      sudo: false
    - perl: "system"
      os: osx
  allow_failures:
    - perl: blead       # ignore failures for blead perl
before_install:
  - export DEVOPS_BRANCH="46-brew-skip-fontconfig-cache"
  - >
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
            export DYLD_FALLBACK_LIBRARY_PATH="blib/lib/auto/share/dist/Alien-FontForge/lib"
    fi
  - eval "$(curl https://raw.githubusercontent.com/project-renard/devops/$DEVOPS_BRANCH/script/helper.pl | perl -- | awk '/^#START/,/^#END/ { print > "/dev/stdout"; next } { print > "/dev/stderr"}' )"
